### ISSUE TITLE
Data example p_model_drivers and p_model_validation: obsolete variables

### ISSUE THREAD

**Issue by pepaaran** [computationales/rsofun#91]
Clean the site_info variables:
- year_start is missing already
- year_end is not used in the `pmodel_use.Rmd` vignette
- date_start - is it ever used? In `prepare_setup_sofun.R` it's overwritten by year_start
- date_end - same

Reduce to the necessary variables only and document all function inputs and outputs. Do these variables refer to the data available in the original files or the date from which the data should be taken to create the appropriate `rsofun` nested data frames?

**Comment by stineb** [comment]
You can check in `run_pmodel_f_bysite.R` which variables are used or overwritten or not used at all. From the df `site_info`, only `lon, lat, elv, whc` are used. 

Only full years can be simulated by rsofun. This is due to the structure of the model. 

The df `forcing` contains the dates for the simulations and it is checked in `run_pmodel_f_bysite` whether this conforms with the info given in `params_siml` (`firstyeartrend, nyeartrend`). This is actually a bit of a legacy from old code. So the two variables `firstyeartrend, nyeartrend` could be dropped altogether, and instead set dynamically based on dates in `forcing`. But a test must be kept to make sure that `forcing` contains only full years (all days of years). Note also that rsofun handles only years with 365 days. Therefore, February 29 is ignored, but I can't recall at this moment where and how.

**Comment by pepaaran** [comment]
Fixed with pull request #102
