### ISSUE TITLE
Equivalent to `collect_drivers_rsofun()` for validation data MISSING

### ISSUE THREAD

**Issue by pepaaran** [computationales/rsofun#92]
The documentation for `calib_sofun()` mentions that the `obs` argument (providing the observational data) should be the output of a `get_obs_calib2()` function. This function does not exist in `rsofun`. 

An equivalent to `collect_drivers_rsofun()` should be created for the observational validation/calibration data, in order to fix the format that is accepted into `calib_sofun()`, `runread_pmodel_f()`...

**Comment by stineb** [comment]
We should design `calib_sofun()` so that the `settings` and the `obs` arguments conform with the ideas laid out [here](https://www.notion.so/computationales/Data-processing-formatting-19bb278088fc4bb58979017b1d5e5543). Here is my suggestion (@khufkens @pepaaran):

To avoid this being infinitely flexible (and requiring complicated code), we should design this around _protocols_ that define:

- the settings list that essentially defines the protocol (or multiple protocols). 
- the target data `obs` (site locations, years, variable, time scale), provided in a static manner outside rsofun  
- the cost function, which is specific for each protocol, and specifies the set of calibrated parameters in a static manner 

```r
settings <- list(
  protocol          = c("fluxnet"),    # this triggers the use of variable GPP and potentially others (ET) in the future
  metric              = list(fluxnet = cost_fluxnet),  # list with elements named in correspondence with 'protocol'
  dir_results         = "./",
  name                = "my_calibration_for_fluxnet",
  control = list(
    sampler = "DEzs",
    settings = list(
      burnin = 500,
      iterations = 1500
    )),
  par = list(
    kphio = list(lower=0.04, upper=0.1, init = 0.05)   # must correspond to the parameters being calibrated by the selected cost function. Must be transparently explained and checked by the code.
    )
)
```
Note that the following are dropped as a result of the simplification with _protocols_: 
```r
   method              = "bayesiantools",   # we may just make BT the default and only option
   timescale           = list(targets_obs = "y"),  # is given by 'protocol'
```
In this sense, we don't need a function to collect `obs`. It's static and given outside rsofun.

This should eventually also work with multiple protocols used simultaneously for calibration. The settings would then look like this (example second protocol being `leaftraits`):
```r
settings <- list(
  protocol          = c("fluxnet", "leaftraits"),
  metric              = list(fluxnet = cost_fluxnet, leaftraits = cost_leaftraits),
  dir_results         = "./",
  name                = "my_fancy_multitarget_calibration",
  control = list(
    sampler = "DEzs",
    settings = list(
      burnin = 500,
      iterations = 1500
    )),
  par = list(
    kphio = list(lower=0.04, upper=0.1, init = 0.05),
    beta = list(lower = 50, upper = 500, init = 150),
    ... # additional parameter made calibratable thanks to additional protocol
    )
)

**Comment by khufkens** [comment]
Looks good but I would only keep in `settings` what are true settings. 

For example the function has no need to return data to file. This should be done after parameterization. Putting this in the settings will create bad behaviour of dumping stuff to file in various nontransparent/haphazard ways.

Better to return the data (which can then be written to file by the user themselves). This further removes the requirement of an additional parameter `name` to be included. Less complexity, less maintenance and more consistency with settings only dealing with things that have to do with the cost function and how it is interpreted.

```r
settings <- list(
  protocol          = c("fluxnet", "leaftraits"),
  metric              = list(fluxnet = cost_fluxnet, leaftraits = cost_leaftraits),
  control = list(
    sampler = "DEzs",
    settings = list(
      burnin = 500,
      iterations = 1500
    )),
  par = list(
    kphio = list(lower=0.04, upper=0.1, init = 0.05),
    beta = list(lower = 50, upper = 500, init = 150),
    ... # additional parameter made calibratable thanks to additional protocol
    )
)

```

**Comment by khufkens** [comment]
As a side note, I don't think it is possible to run multiple protocols together as you envision it. There is one cost function only to be run per optimization. This can be a wrapper around two other cost functions with their results conditionally merged but this is limited in flexibility, or should be from our part as this needs careful consideration.


```r
cost_fluxnet <- function(){}
cost_leaftraits <- function(){}

cost_protocol <- function(){
 cost_1 <- cost_fluxnet()
 cost_2 <- cost_leaftraits()

 total_cost  <- cost_1 + cost_2
}
```
